
/* Chapter 4 Compound Types, Programming Exercises # 8
 Pizza-analysis service. For each pizza, he needs to record the following information:
 1. The name of the pizza company, which can consist of more than one word
 2. The diameter of the pizza
 3. The weight of the pizza
 Devise a structure that can hold this information and write a program that uses a structure variable of that type.The program should ask the user to enter each of the preceding items of information, and then the program should display that information. Use cin (or its methods) and cout.
 Use new to allocate a structure instead of declaring a structure variable.Also have the program request the pizza diameter before it requests the pizza company name.
 */

#include <iostream>
#include <string>
using namespace std;
struct pizza
{
    string name;
    double diameter;
    double weight;
};
void f(pizza * pi);

int main()
{
    pizza * pi = new pizza;
    f(pi);
    
    delete pi;
    return 0;
}

void f(pizza * pi)
{
    cout << "Enter the pizza's diameter: ";
    cin >> pi->diameter;
    cin.get();//or (cin >> pi.diameter)get.()
    /*  The problem is that when cin reads the pi.diameter, it leaves the newline generated by the Enter ke  in the input queue. Then cin.getline() reads the newline as an empty line and assigns a null string to the piname string.The fix is to read and discard the newline before reading the address.*/
    
    cout << "Enter the pizza company name: ";
    getline(cin, pi->name);
    cout << "Enter the pizza's weight: ";
    cin >> pi->weight;
    
    cout << "Here is the info about the pizza:\n";
    cout << "Company name: " << pi->name << endl;
    cout << "Pizza's diameter: " << pi->diameter << "inches" << endl;
    cout << "Pizza's weight: " << pi->weight << "lbs" << endl;
}
